### PR TITLE
Created a word rain game and balloon pop game using hooman library

### PR DESCRIPTION
**Pull request by vamsipasam2000**
In the word rain game, letters of the alphabet fall from the top of the screen, and players must press the corresponding keys to "catch" them before they reach the bottom. Each successful catch increases the player's score.

The Balloon Pop game is a simple and entertaining game designed for players of all ages. The concept revolves around popping balloons that float upwards on the screen. Each balloon has a random size and ascends at a random speed. Players must click on these balloons to pop them, earning points for each successful pop. The scoring system rewards more points for smaller balloons, adding a fun challenge to the gameplay. The game's objective is to pop as many balloons as possible, enhancing the player's coordination and reaction skills. To play, simply click on the balloons as they appear and move up the screen. The game continues until the player chooses to exit, with the score displayed continuously, allowing players to track their progress and aim for higher scores.

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
@vamsipasam2000 can you please remove the .DS files? Thanks!

**Comment by vamsipasam2000** [comment]
@Abdur-rahmaanJ I believe I have removed the .DS files in the recent commit and only added the wordrain.py file and updated the pull request #84 Kindly review the changes and let me know if any further modifications needed. Otherwise please do the merge. Thank you.

**Comment by vamsipasam2000** [comment]
@Abdur-rahmaanJ I have also added a new balloon pop game using the hooman library. Kindly review the changes and please merge the pull requests #84  if no issues found. Thank you!

**Comment by Abdur-rahmaanJ** [comment]
@vamsipasam2000 You deleted the .gitignore file in your pull request, can you please restore it? thanks!

**Review by Abdur-rahmaanJ — APPROVED** [review]
Both programs are quite innovative!

**Pull request merged**
