### PR TITLE
Added calculatordemo.py

### PR DESCRIPTION
**Pull request by chandana1221**
I have added calculatordemo.py in hooman/demos

### CODE REVIEW

**Comment by chandana1221** [comment]
Hello @Abdur-rahmaanJ , I have added calculatordemo.py to hooman/demos folder. Can you please merge it.

**Review by TheBigKahuna353 — COMMENTED** [review]
Hey, calculatordemo.py doesnt use hooman, so not gonna add it to the hooman demos folder

**Comment by chandana1221** [comment]
Hy Jordan,

Can you please let me know in which folder can I add calculator demo.py

Thanks
Chandana P.

**Comment by TheBigKahuna353** [comment]
this is the hooman respository, so everything here is about hooman. 

you can try find a TKinter repository that has demos or create your own repository and upload it there!

**Pull request closed without merging**
